@startuml

title Activity Diagram \n

start

:testing;

note left
    This is a Note...
    * Activity diagrams can begin with a Start
    * An activity is colon, some words, and a semicolon
    * Activity diagrams can end with a stop
end note

:Drink Homebrew;

stop

@enduml