version : '3'
services:
  fill:
    build: ./php
    image: project_php:latest
    container_name: fill
    hostname: "fill"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx_fill:
    build: ./nginx
    image: nginx_fill:latest
    container_name: nginx_fill
    hostname: "nginx_fill"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fill
