@startuml encapsulation

class Jam {
    __ private data__
    - Jam : int
    - Menit : int
    - Detik : int
    __ callback__
    + displayJam()
    __ set data__
    + tambahJam()
    + tambahMenit()
    + tambahDetik()
    --
    source code pert5-0.cc
}
note left of Jam::Jam
  Private Class
end note

note left of Jam::displayJam()
  Callback Template
end note

note left of Jam::tambahJam()
  Logic Template
end note

header 
Pertemuan 5
endheader
caption copyright@esaunggul.ac.id
legend left
    CTI211-Pemograman Berorientasi Objek 
endlegend
@enduml